name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Jekyll dependencies
        run: |
          gem install jekyll github-pages webrick unicode_utils
          gem install jekyll-email-protect jekyll-feed jekyll-github-metadata
          gem install jekyll-paginate-v2 jekyll-scholar jekyll-twitter-plugin
          gem install jekyll-sitemap jemoji

      - name: Build site
        run: jekyll build --source . --destination ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
